# Generated by Django 5.1.1 on 2024-09-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional', models.CharField(max_length=50)),
                ('simplified', models.CharField(max_length=50)),
                ('pinyin', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=200)),
            ],
        ),
    ]
