# Generated by Django 5.0.7 on 2024-08-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traditional', models.CharField(max_length=50)),
                ('simplified', models.CharField(max_length=50)),
                ('pinyin', models.CharField(max_length=50)),
                ('english', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
